=== Loriv3/1933943_LoAP/source/resources/schemas/iot/rest/rest.chemistry.v1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "rest.chemistry.v1",
    "type": "object",
    "properties": {
        "sensor_id": {
            "type": "string",
            "description": "The sensor this data refers to.",
            "pattern": "^[^\\.]$"
        },
        "captured_at": {
            "type": "string",
            "format": "date-time",
            "pattern": "^[0-9\\-]+T[0-9:]+\\.[0-9]+(Z|\\+[0-9:]+)?$",
            "description": "The time at which this measurement was captured."
        },
        "measurements": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "metric": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "unit": {
                        "type": "string"
                    }
                },
                "required": [
                    "metric",
                    "value",
                    "unit"
                ]
            },
            "minItems": 1
        },
        "status": {
            "enum": [
                "ok",
                "warning"
            ]
        }
    },
    "required": [
        "sensor_id",
        "captured_at",
        "measurements",
        "status"
    ]
}

=== Loriv3/1933943_LoAP/booklets/api_samples/iot/api/sensors/schemas/rest.chemistry.v1-2.json
{
    "sensor_id": "air_quality_voc",
    "captured_at": "2026-03-06T00:19:01.673715+00:00",
    "measurements": [
        {
            "metric": "voc_ppb",
            "value": 596.03,
            "unit": "ppb"
        },
        {
            "metric": "co2e_ppm",
            "value": 569.2,
            "unit": "ppm"
        }
    ],
    "status": "ok"
}
