=== Loriv3/1933943_LoAP/source/resources/schemas/iot/topic/topic.environment.v1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "topic.environment.v1",
    "type": "object",
    "properties": {
        "topic": {
            "type": "string",
            "description": "The topic this data refers to.",
            "pattern": "^[^\\.]$"
        },
        "event_time": {
            "type": "string",
            "format": "date-time",
            "pattern": "^[0-9\\-]+T[0-9:]+\\.[0-9]+(Z|\\+[0-9:]+)?$",
            "description": "The time at which this event was emitted."
        },
        "source": {
            "type": "object",
            "description": "This event's source's information.",
            "properties": {
                "system": {
                    "type": "string",
                    "pattern": "^[^\\.]$"
                },
                "segment": {
                    "type": "string",
                    "pattern": "^[^\\.]$"
                }
            },
            "required": [
                "system",
                "segment"
            ]
        },
        "measurements": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "metric": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "unit": {
                        "type": "string"
                    }
                },
                "required": [
                    "metric",
                    "value",
                    "unit"
                ]
            },
            "minItems": 1
        },
        "status": {
            "enum": [
                "ok",
                "warning"
            ]
        }
    },
    "required": [
        "topic",
        "event_time",
        "source",
        "measurements",
        "status"
    ]
}

=== Loriv3/1933943_LoAP/booklets/api_samples/iot/api/telemetry/schemas/topic.environment.v1-3.json
{
    "topic": "mars/telemetry/life_support",
    "event_time": "2026-03-06T00:01:18.531242+00:00",
    "source": {
        "system": "life-support",
        "segment": "habitat-alpha"
    },
    "measurements": [
        {
            "metric": "oxygen_percent",
            "value": 19.49,
            "unit": "%"
        }
    ],
    "status": "warning"
}

=== Loriv3/1933943_LoAP/booklets/api_samples/iot/api/telemetry/schemas/topic.environment.v1-1.json
{
    "topic": "mars/telemetry/radiation",
    "event_time": "2026-03-06T00:00:03.469786+00:00",
    "source": {
        "system": "radiation-monitor",
        "segment": "habitat-alpha"
    },
    "measurements": [
        {
            "metric": "radiation_uSv_h",
            "value": 0.21,
            "unit": "uSv/h"
        }
    ],
    "status": "ok"
}
